### ISSUE TITLE
268 missing number

### ISSUE THREAD

**Issue by Rwatana** [Rwatana/leet_code_Review#26]
## Summary
add 268 missing number
## Goal
add 268 missing number

## Todo

- [ ] add 268 missing number
- [ ] write time and space complexity

## Deadline
10/24
## Parent issue
https://github.com/okuda-seminar/Engineering/issues/599
## References
None
add 378_Kth smallest element in a sorted matrix
## Todo

- [ ] add 378_Kth smallest element in a sorted matrix
- [ ] write time and space complexity

## Deadline
10/24
## Parent issue
https://github.com/okuda-seminar/Engineering/issues/599
## References
None

## Notes
None
